### ISSUE TITLE
Mappings.bam Doesn't open in IGV

### ISSUE THREAD

**Issue by timp0** [nanoporetech/megalodon#113] opened 2021-03-05 15:29 UTC
Another question: 

When I run:

!megalodon subset_f5 --processes 10 --outputs mappings variants variant_mappings per_read_variants \
    --reference {ref} --variant-filename {variants} --output-directory try2 \
    --guppy-server-path /usr/bin/guppy_basecall_server --reads-per-guppy-batch 10 --devices 0 

The mappings.bam (after sorting and indexing) doesn't  open in IGV, or rather it opens with an empty track.  In contrast, the variants_mapping.bam opens fine.  Is the problem that I asked for both bams?  Confused about what the issue is specifically, inspection of the bams suggests they are properly formed on a quick examination.

**Comment by marcus1487** [comment] 2021-03-05 21:34
This is odd indeed. I'll try to reproduce this myself. I know I've been able to load the mappings BAM in IGV, but not tested specifically when outputting both mappings and variant_mappings (though the should not be affecting one another).

Aside: you can have megalodon sort and index the mappings with the `--sort-mappings` flag. This will spawn a process to run while variant aggregation is proceeding. This just runs samtools in a subprocess. This should run sorting and mapping on all mapping outputs. I turned this off by default as it can take a while for larger runs and more specific multiprocessing/memory allocation parameters may be warranted, but the option is there to simplify your pipeline!

P.S. Thanks for the issue logging!

**Comment by marcus1487** [comment] 2021-03-10 21:56
I'm not able to replicate this issue. Any chance you solved it, @timp0 ? I am using the `--sort-mappings` flag in megalodon. Maybe it has to do with the sorting/indexing on the command line (though that would be quite odd; a.k.a. just another day in bioinformatics).

**Comment by timp0** [comment] 2021-04-01 13:50
Nope still not solved.  I wonder if it's linked to the invalid characters that it's reporting for the variant calling (Issue #112 ) - the reference I'm using here is just chrM from hg38.

**Comment by marcus1487** [comment] 2021-04-01 16:30
Given the issue in #112 I would expect this issue to be the other way around (regular `mappings.bam` should work and `variant_mappings.bam` would be empty). I'll have a look to see if these outputs.

**Comment by marcus1487** [comment] 2021-04-01 23:09
Looking at the code i'm not sure how this error could be reached in standard processing. I think this might have been fixed in development since the latest release. Could you try to latest release (2.3.0), which was just pushed to see if the issue is resovled.

**Comment by marcus1487** [comment] 2021-04-26 18:51
@timp0 , Any chance you've had a go at this with the most recent version?

**Comment by marcus1487** [comment] 2021-04-29 17:16
Closing as I believe this issue has been resolved. Please re-open if this issue persists.

**Closed by marcus1487** 2021-04-29 17:16 UTC
Labels: bug
