### ISSUE TITLE
BAM encoding for quality "*"

### ISSUE THREAD

**Issue by jkbonfield** [nanoporetech/megalodon#56] opened 2020-09-17 09:09 UTC
I'm not sure if this project is the one doing the writing, or whether it's in something else (eg pyguppy or even pysam), so feel free to move this issue wherever it is appropriate.

The BAM specifications states that "_When base qualities are omitted but the sequence is not, qual is filled with 0xFF bytes (to length l_seq)_".

The mod_basecalls.bam and mod_mappings.bam files produced have the first qual as 0xFF and all subsequent quals as 0x00.  This makes Samtools (and other tools) report "*" in SAM, but it's not technically adhering to the specification.

Where it matters is things like the pileup interface.  Here we do random access into the quality string, and find qual 0 for most calls.  The hope is that any base showing qual 255 will be treated as unknown by whatever tool is processing it and given a fixed confidence value (for example).  Qual 0 in phred scale basically means the chance of error is 100%, ie you are absolutely certain every base call is incorrect!  (Thus for non-N it's also a reasonable proxy for unknown given the nonsensical nature of it, but in practice I have seen basecalling software emit qual 0 for low quality bases before, so that's not too robust.)

Regards.

**Comment by marcus1487** [comment] 2020-09-17 13:51
I see this behavior with the mod_mappings.bam output, but not the mod_basecalls.bam. mod_basecalls.bam should have the basecalling quality values as found in the basecalls.fastq output. Let me know if you do indeed see the `*` quality value in the mod_basecalls.bam output.

For the mod_mappings.bam, Megalodon is using pysam to output the mappings. The quality scores are left as `None` which produces this behavior. This is likely a bug in pysam, but can also be easily fixed in Megalodon. I will push a fix for this shortly and include this in the next release.

**Comment by marcus1487** [comment] 2020-09-17 14:14
I have pushed a fix for this issue to the `null_map_qual_fix` branch. This runs without error, but I can't tell if the issue is solved. When viewing the output mod_mappings.bam file with samtools, the base qualities field still shows as `*`. @jkbonfield could you confirm that this branch fixes the issue?

**Comment by jkbonfield** [comment] 2020-09-17 14:34
If it's a pysam issue I will raise it there then.  Thanks.

**Comment by jkbonfield** [comment] 2020-09-17 14:35
Sorry I should have replied to the 2nd comment too.  The easiest way to determine if it fixes it is just to zcat the BAM and pipe into less (or `hd`).  You should see a bunch of 0xff instead of 0xff followed by a bunch of 0x00.

**Closed** 2020-09-18 16:16 UTC
