### ISSUE TITLE
 ERROR: Guppy server initialization failed. See guppy logs in [--output-directory] for more details.

### ISSUE THREAD

**Issue by Fatihlrcfs** [nanoporetech/megalodon#207] opened 2021-10-28 13:56 UTC
hi dear,

I am working on megalodon in Linux with a CPU option and could not pass the error.  Also, my log file did not help to figure out what is the error. you can see the error below. Thanks and great days

Best. 

[14:43:33] Running Megalodon version 2.3.4
DBG 14:43:33 : Command: """/cluster/lrcfs/ftiras/ftiras_env/envs/nanoplot/bin/megalodon fast5/ --outputs mods --reference wholegenome --mod-motif m CG 0 --write-mods-text --processes 10 --guppy-server-path /cluster/lrcfs/ftiras/bin/ont-guppy-cpu-5.0.16/bin/guppy_basecall_server --guppy-params -d ./cluster/lrcfs/2397405/bin/rerio/basecall_models/ --num_callers 10 --guppy-timeout 400 --guppy-config res_dna_r941_min_modbases_5mC_CpG_v001.cfg --overwrite""" --- MainProcess-MainThread megalodon.py:1750
[14:43:33] Loading guppy basecalling backend
DBG 14:43:33 : Guppy version: "5.0.16" --- MainProcess-MainThread backends.py:869
DBG 14:43:33 : Pyguppy version: "5.0.16" --- MainProcess-MainThread backends.py:870
DBG 14:43:33 : guppy server init command: "/cluster/lrcfs/ftiras/bin/ont-guppy-cpu-5.0.16/bin/guppy_basecall_server -p auto -l megalodon_results/guppy_log -c res_dna_r941_min_modbases_5mC_CpG_v001.cfg --post_out --quiet -d ./cluster/lrcfs/2397405/bin/rerio/basecall_models/ --num_callers 10" --- MainProcess-MainThread backends.py:944
****************************************************************************************************
	ERROR: Guppy server initialization failed. See guppy logs in [--output-directory] for more details.
		Try running the guppy server initialization command found in log.txt in order to pinpoint the source of this issue.
****************************************************************************************************

**Comment by marcus1487** [comment] 2021-11-01 13:50
This is a duplicate of previous issues (see https://github.com/nanoporetech/megalodon/issues/197#issuecomment-944419446)

The quoted `--guppy-params` option does not get expanded. Please provide the full path for the `-d` argument.

**Closed by marcus1487** 2021-11-01 13:50 UTC
Labels: duplicate
