### ISSUE TITLE
Guppy version string does not match expected pattern

### ISSUE THREAD

**Issue by PanZiwei** [nanoporetech/megalodon#98] opened 2021-02-18 19:50 UTC
Hi, I am trying to use Megalodon to train a Modified Base Model following the command below provided by the [tutorial](https://nanoporetech.github.io/megalodon/modbase_training.html):
```shell
megalodon ecoli_k12_fast5s/ \
    --outputs signal_mappings \
    --reference ecoli_k12_reference.fa \
    --devices 0 --processes 40 \
    --ref-mods-all-motifs m 5mC CCWGG 1 \
    --guppy-server-path ${GUPPY_PATH}/guppy_basecall_server \
    --devices 0 \
    --processes ${NPROC}   
```
But I got the error saying "Guppy version string does not match expected pattern":
```
[11:29:08] Running Megalodon version 2.2.10
[11:29:08] Loading guppy basecalling backend
****************************************************************************************************
        ERROR: Guppy version string does not match expected pattern: "b'Intel MKL FATAL ERROR: Cannot load ont-guppy-gpu_4.2.2/bin/guppy_basecall_server.\n'"
****************************************************************************************************
```
Any idea on the same issue? I am using Megalodon v2.2.10, Guppy 4.2.2 and ont-pyguppy-client-lib 4.2.2.

Also, if I had two samples with different modifications, is it possible to train them separately and integrate the model later?

Thank you so much for your help!

**Comment by marcus1487** [comment] 2021-02-18 20:06
This looks like a guppy hardware compatibility issue. Could you try to run the guppy server initialization command found near the top of the megalodon log file? If this reproduces the error could you report this to the nanopore community or contact technical support?

For the samples with different modifications, the training datasets can be constructed separately and merged within taiykai by using the `taiyaki/misc/merge_mappedsignalfiles.py` script. This script contains options to merge the alphabets for the different modified bases as well (see `taiyaki/misc/merge_mappedsignalfiles.py -h`)

**Comment by PanZiwei** [comment] 2021-02-18 20:24
Hi, can you explain in more details? So I should test whether Guppy under the guppy server path can work or not?

**Comment by marcus1487** [comment] 2021-02-19 00:54
Yes I am proposing to check whether the standalone guppy server works on your machine (using the same command that failed under the hood within megalodon). The exact command run by megalodon to start the guppy server can be found at the top of the megalodon log file produced from this command.

Megalodon requires the guppy config for most all run modes (reading from pre-called FAST5s and using the taiyaki basecalling backend are the two exceptions). The signal mappings are to reference bases derived from basecalling and then mapping the basecalls to the reference. The signal mapping is also derived from the basecaller intermediate output. So the guppy model/config is involved in several steps of this command even though basecalls and/or mappings are not saved as outputs.

**Comment by PanZiwei** [comment] 2021-02-19 01:15
For Guppy issue:
I checked on my own machine on an interactive GPU node with the following command:
```shell
cd ont-guppy-gpu_4.2.2/bin/
guppy_basecall_server
```
After submitting `guppy_basecall_server`, it initiates the help document for `guppy_basecall_server`(See the snapshot below). In this case, I think standalone guppy server works?
![Screen Shot 2021-02-18 at 8 10 33 PM](https://user-images.githubusercontent.com/44417006/108442650-617efa00-7225-11eb-9158-e88a19daeba2.png)

For Guppy config:
1. Is there a default model will be called since your tutorial for the model training script actually didn't have the option for `--guppy-config`?
2. To my understand Megalodon uses config to get the base caller intermediate output, so it is necessary to have the base call information. The base calling information can be either achieved by base calling step via Guppy or Taiyaki, or use other tools to pre-called FAST5(which means that base call information is already saved in FAST5)?

**Comment by PanZiwei** [comment] 2021-02-19 05:13
### Update for Guppy issue:  I got `ERROR: Guppy server initialization failed.` instead

I change the working directory to the Guppy and rerun the script below:
```
module unload cuda10.1/toolkit

source /projects/li-lab/Ziwei/Anaconda3/etc/profile.d/conda.sh
conda activate megalodon2.2.10_guppy4.2.2

FAST5_PATH="/data/"
OUTPUT_DIR="/results/megalodon_model"
GUPPY_PATH="/ont-guppy-gpu_4.2.2/bin"
SAMTOOLS_PATH='megalodon2.2.10_guppy4.2.2/bin/samtools'

megalodon ${FAST5_PATH}/ \
    --outputs signal_mappings \
    --output-directory ${OUTPUT_DIR} \
    --overwrite \
    --reference ecoli_k12_reference.fa \
    --devices 0 --processes 40 \
    --ref-mods-all-motifs m 5mC CCWGG 1 \
    --guppy-server-path ${GUPPY_PATH}/guppy_basecall_server \
    --devices 0 \
    --processes 40
```

This time I got `ERROR: Guppy server initialization failed.`,  the same as my previous issue on Guppy v4.4.1 #86, but the Guppy version is different. It is really weird since I had run Guppy v4.2.2 before and everything worked before except now.
``
****************************************************************************************************
	ERROR: Guppy server initialization failed. See guppy logs in --output-directory for more details.
		Try running the guppy server initialization command found in log.txt in order to pinpoint the source of this issue.
****************************************************************************************************
```
Here is the `log.txt`:
```
[23:53:11] Running Megalodon version 2.2.10
DBG 23:53:11 : Command: """megalodon2.2.10_guppy4.2.2/bin/megalodon /data/ --reference /reference/Ecoli.fa --output-directory /megalodon_model --overwrite --ref-mods-all-motifs m 5mC CCWGG 1--outputs signal_mappings mod_mappings mappings --guppy-server-path ont-guppy-gpu_4.2.2/bin/guppy_basecall_server --guppy-params --num_callers 10 --ipc_threads 80 --guppy-timeout 500 --samtools-executable /megalodon2.2.10_guppy4.2.2/bin/samtools --sort-mappings --mappings-format bam --devices 0 --processes 40""" --- MainProcess-MainThread megalodon.py:1240
[23:53:11] Loading guppy basecalling backend
DBG 23:53:11 : Guppy version: "4.2.2" --- MainProcess-MainThread backends.py:541
DBG 23:53:11 : Pyguppy version: "4.2.2" --- MainProcess-MainThread backends.py:542
DBG 23:53:11 : guppy server init command: "/ont-guppy-gpu_4.2.2/bin/guppy_basecall_server -p auto -l /results/megalodon_model/guppy_log -c dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg --post_out -x cuda:0 --num_callers 10 --ipc_threads 80" --- MainProcess-MainThread backends.py:599
****************************************************************************************************
        ERROR: Guppy server initialization failed. See guppy logs in --output-directory for more details.
                Try running the guppy server initialization command found in log.txt in order to pinpoint the source of this issue.
****************************************************************************************************

**Comment by PanZiwei** [comment] 2021-02-19 05:14
@fbrennen 
Hi, for some reason I can't log in to the Nanopore Community support pages and I am waiting for the response from the support team. At the same time, can you help with the Guppy error above?

What I have tried:
1. Check Guppy version to make sure it is v4.2.2
I found the error is raised from:
https://github.com/nanoporetech/megalodon/blob/d6e729c7a3d3f3fdc8b161087438d66636815f7b/megalodon/backends.py#L534-L540
But when I checked Guppy version, it is indeed v4.2.2(See below):
```
(megalodon2.2.10_guppy4.2.2) [c-panz@winter200 scripts]$ cd /ont-guppy-gpu_4.2.2/bin
(megalodon2.2.10_guppy4.2.2) [c-panz@winter200 bin]$ guppy_basecaller --version
: Guppy Basecalling Software, (C) Oxford Nanopore Technologies, Limited. Version 4.2.2+effbaf8
(megalodon2.2.10_guppy4.2.2) [c-panz@winter200 bin]$ guppy_basecall_server --version
: Guppy Basecall Service Software, (C) Oxford Nanopore Technologies, Limited. Version 4.2.2+effbaf8, client-server API version 3.2.0
```
And I tried to 

2. Swtich to Guppy 4.4.1: Fail to use v4.4.1
I got the error when initiate Guppy 4.4.1:
```
[guppy/error] main: CuBLAS error at /builds/ofan/ont_core_cpp/ont_core/basecall_core/nn_caller_cuda.cpp:1138: 1
[guppy/warning] main: An error has occurred. Aborting.
```
I think the reason is that I don’t currently have CUDA 11.1 / driver version 455 CUDA 11 installed or available as a module since you mentioned that it is required for Guppy v4.4.1 in #86 

3. install `pyguppyclient` as suggested in #91, but the latest version only supports Guppy v4.4.1, so I uninstalled it.

**Comment by fbrennen** [comment] 2021-02-19 08:18
Hi @PanZiwei -- have you tried `pip install ont-pyguppy-client-lib==4.2.2`? That should allow you to install a specific client library version. There is nothing in your server log indicating an issue with the guppy server, so if you can install the correct client library version then I would hope everything will work.

**Comment by marcus1487** [comment] 2021-02-19 13:56
The pyguppy version appears to match from the megalodon log file. Could you try to run the guppy server initialization command outside of megalodon. This command as listed in the megalodon log is: `/ont-guppy-gpu_4.2.2/bin/guppy_basecall_server -p auto -l /results/guppy_log -c dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg --post_out -x cuda:0 --num_callers 10 --ipc_threads 80`

**Comment by PanZiwei** [comment] 2021-02-19 14:51
@fbrennen 
Yeah, I tried this step before and I double-check the ont-pyguppy-client-lib version, it is indeed 4.2.2.
```
(megalodon2.2.10_guppy4.2.2) [c-panz@winter200 ~]$ conda list ont-pyguppy-client-lib
# packages in environment at /projects/li-lab/Ziwei/Anaconda3/envs/megalodon2.2.10_guppy4.2.2:
#
# Name                    Version                   Build  Channel
ont-pyguppy-client-lib    4.2.2                    pypi_0    pypi
```

Hi @marcus1487 ,
I tried the command you suggest on an interactive node and got a CUDA error below. So it seems to be the CUDA version?
I checked the CUDA version and my highest is cuda10.1/toolkit/10.1.243.
```
(megalodon2.2.10_guppy4.2.2) [c-panz@winter200 ~] $module load cuda10.1/toolkit
(megalodon2.2.10_guppy4.2.2) [c-panz@winter200 ~]$ /ont-guppy-gpu_4.2.2/bin/guppy_basecall_server -p auto -l /results/guppy_log -c dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg --post_out -x cuda:0 --num_callers 10 --ipc_threads 80
ONT Guppy basecall server software version 4.2.2+effbaf8, client-server API version 3.2.0
config file:         /ont-guppy-gpu_4.2.2/data/dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg
model file:          /ont-guppy-gpu_4.2.2/data/template_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.jsn
log path:            /results/guppy_log
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     10
num socket threads:  80
max returned events: 50000
gpu device:          cuda:0
kernel path:
runners per device:  4

[guppy/error] main: CUDA error at /builds/ofan/ont_core_cpp/ont_core/common/cuda_common.h:111: CUDA_ERROR_INVALID_VALUE
[guppy/warning] main: An error occurred initialising the basecaller. Aborting.
```

**Comment by fbrennen** [comment] 2021-02-19 15:36
Hi @PanZiwei -- those are some aggressive guppy parameters you're using. I'd start by not specifying anything you don't have to when launching the server -- leave out things like `--num_callers` and `--ipc_threads`.

**Comment by PanZiwei** [comment] 2021-02-19 15:39
@fbrennen 
It still happens even though I leave out the parameters and use the default ones...
```
(megalodon2.2.10_guppy4.2.2) [c-panz@winter200 ~]$ module load cuda10.1/toolkit
(megalodon2.2.10_guppy4.2.2) [c-panz@winter200 ~]$ /ont-guppy-gpu_4.2.2/bin/guppy_basecall_server -p auto -l /results/guppy_log -c dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg --post_out -x cuda:0
ONT Guppy basecall server software version 4.2.2+effbaf8, client-server API version 3.2.0
config file:         /ont-guppy-gpu_4.2.2/data/dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg
model file:          /ont-guppy-gpu_4.2.2/data/template_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.jsn
log path:            /results/guppy_log
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:
runners per device:  4

[guppy/error] main: CUDA error at /builds/ofan/ont_core_cpp/ont_core/common/cuda_common.h:111: CUDA_ERROR_INVALID_VALUE
[guppy/warning] main: An error occurred initialising the basecaller. Aborting.
```

**Comment by fbrennen** [comment] 2021-02-19 16:06
Hi @PanZiwei -- have you ever managed to basecall *anything* successfully with guppy using those parameters?  I would recommend experimenting with them for a bit until you can get that to work -- you should be able to, as long as you don't accidentally tell guppy to use that one GPU which has no memory available (try changing the zero in `cuda:0` to other values).

**Comment by PanZiwei** [comment] 2021-02-19 16:20
Hi @fbrennen Yeah I **had use Guppy v4.2.2 for basecalling with no problem** in the past. I just have another test and it indeed work still. See the command below:
```
$guppy_dir/bin/guppy_basecaller --input_path $fast5_dir/0 --save_path $output_dir/0 --config dna_r9.4.1_450bps_hac.cfg --fast5_out --verbose_logs --device auto
(megalodon2.2.10_guppy4.2.2) [c-panz@winter200 ont-guppy-gpu_4.2.2]$ $guppy_dir/bin/guppy_basecaller --input_path $fast5_dir/0 --save_path $output_dir/0 --config dna_r9.4.1_450bps_hac.cfg --fast5_out --verbose_logs --device auto
ONT Guppy basecalling software version 4.2.2+effbaf8
config file:        /ont-guppy-gpu_4.2.2/data/dna_r9.4.1_450bps_hac.cfg
model file:         /ont-guppy-gpu_4.2.2/data/template_r9.4.1_450bps_hac.jsn
input path:         /data/0
save path:          /test/0
chunk size:         2000
chunks per runner:  512
records per file:   4000
num basecallers:    4
gpu device:         auto
kernel path:
runners per device: 4

Found 200 fast5 files to process.
Init time: 5594 ms

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Caller time: 9444 ms, Samples called: 25738005, samples/s: 2.72533e+06
Finishing up any open output files.
Basecalling completed successfully.
```

However, when I changed the value `cuda:0` into `cuda:1` or `cuda:2` or `cuda:auto`, I STILL got the CUDA error.
```
[guppy/error] main: CUDA error at /builds/ofan/ont_core_cpp/ont_core/common/cuda_common.h:111: CUDA_ERROR_INVALID_VALUE
[guppy/warning] main: An error occurred initialising the basecaller. Aborting.
```

**Comment by marcus1487** [comment] 2021-02-23 19:03
Does megalodon run with `--devices 0`?

**Comment by PanZiwei** [comment] 2021-02-24 14:16
@marcus1487,
No it didn't. I got the error below:
```
2021-02-24 09:13:59.699928 [guppy/message] ONT Guppy basecall server software version 4.2.2+effbaf8, client-server API version 3.2.0
config file:         /ont-guppy-gpu_4.2.2/data/dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg
model file:         /ont-guppy-gpu_4.2.2/data/dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.jsn
log path:            /test/guppy_log
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:
runners per device:  4

2021-02-24 09:13:59.701259 [guppy/info] crashpad_handler not supported on this platform.
2021-02-24 09:13:59.707446 [guppy/info] Listening on port 33886.
2021-02-24 09:14:00.159157 [guppy/info] CUDA device 0 (compute 6.0) initialised, memory limit 17071734784B (16795435008B free)
```

**Comment by fbrennen** [comment] 2021-02-24 14:36
Hi @PanZiwei -- are you in a conda environment there? I see that `(megalodon2.2.10_guppy4.2.2)` bit and was wondering. If you are, could you try deactivating it and then running the basecall server? Something like this:

`/ont-guppy-gpu_4.2.2/bin/guppy_basecall_server -p 5559 -l /results/guppy_log -x cuda:0 -c dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg`

And then to do some basecalling:
 
`/ont-guppy-gpu_4.2.2/bin/guppy_basecall_client -p 5559 -c dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg -i /data/0 -s /test/0`

(I pulled the suggestions for log and input/output directories from the bits you've already provided -- they may need updating.)

**Comment by PanZiwei** [comment] 2021-02-24 14:58
Hi @fbrennen ,
Yeah I am in a conda environment. And I tried to deactivate it, then run the command as you suggest on an interactive node. But it seems that I got stuck in the `Starting server on port` step:
```
(base) [c-panz@winter211 software]$ input_dir="/fastscratch/c-panz/test/input"
(base) [c-panz@winter211 software]$ output_dir="/fastscratch/c-panz/test/output"
(base) [c-panz@winter211 software]$ log_dir='/fastscratch/c-panz/test/'
(base) [c-panz@winter211 software]$ ont-guppy-gpu_4.2.2/bin/guppy_basecall_server -p 5559 -l $log_dir -x cuda:0 -c dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg
ONT Guppy basecall server software version 4.2.2+effbaf8, client-server API version 3.2.0
config file:         ont-guppy-gpu_4.2.2/data/dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg
model file:          ont-guppy-gpu_4.2.2/data/template_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.jsn
log path:            /fastscratch/c-panz/test/
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:
runners per device:  4

Starting server on port: 5559
```
And here is the log txt:
```
2021-02-24 09:55:03.175019 [guppy/message] ONT Guppy basecall server software version 4.2.2+effbaf8, client-server API version 3.2.0
config file:         ont-guppy-gpu_4.2.2/data/dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg
model file:          ont-guppy-gpu_4.2.2/data/template_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.jsn
log path:            /fastscratch/c-panz/test/
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:
runners per device:  4

2021-02-24 09:55:03.190412 [guppy/info] crashpad_handler not supported on this platform.
2021-02-24 09:55:03.191989 [guppy/info] Listening on port 5559.
2021-02-24 09:55:03.348406 [guppy/info] CUDA device 0 (compute 6.0) initialised, memory limit 17071734784B (16795435008B free)
```

**Comment by PanZiwei** [comment] 2021-02-24 15:46
I got an error with `/ont-guppy-gpu_4.2.2/bin/guppy_basecall_client -p 5559 -c dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg -i /data/0 -s /test/0`:

```
(base) [c-panz@winter211 software]$ ont-guppy-gpu_4.2.2/bin/guppy_basecall_client -p 5559 -c dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg -i $input_dir -s $output_dir
ONT Guppy basecalling software version 4.2.2+effbaf8, client-server API version 3.2.0
config file:        /ont-guppy-gpu_4.2.2/data/dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg
input path:         /fastscratch/c-panz/test/input
save path:          /fastscratch/c-panz/test/output
chunk size:         2000
records per file:   4000

[guppy/error] guppy::BasecallClient::create_basecall_client: Could not connect to server: Timeout waiting for reply to request: GET_CONFIGS
[guppy/error] guppy::BasecallClient::create_basecall_client: Basecall client not initialised correctly.
[guppy/error] main: Basecall client not initialised correctly.
[guppy/warning] main: An error has occurred. Aborting.
```

**Comment by fbrennen** [comment] 2021-02-24 17:27
Hi @PanZiwei -- your server looks like it launched correctly to me. That's exactly what it's supposed to show, and it doesn't do anything else when you launch it -- you need to keep it running and then connect to it with the basecall client (say, from another terminal). Could you try that?

**Comment by PanZiwei** [comment] 2021-02-24 17:53
Hi @fbrennen ,
I am sorry that I am only allowed 1 interactive node on GPU in my institute, so I can't open two terminal at the same time...Any alternative way to try this?

**Comment by fbrennen** [comment] 2021-02-24 18:19
Sure -- just launch the server in the background:

`guppy_basecall_server <all the other args I listed above> &`

Then you can run the `guppy_basecall_client` command from the same terminal.

https://linuxhandbook.com/run-process-background/

**Comment by PanZiwei** [comment] 2021-02-24 19:53
@fbrennen 
Everything looks good with the `guppy_basecall_server` and `guppy_basecall_client`, see command below. In this case I am really confused about the cause for the initial error raised in the issue...
```
(base) [c-panz@winter211 software]$ input_dir="/fastscratch/c-panz/test/input"
(base) [c-panz@winter211 software]$ output_dir="/fastscratch/c-panz/test/output"
(base) [c-panz@winter211 software]$ log_dir='/fastscratch/c-panz/test/'
(base) [c-panz@winter211 software]$ ont-guppy-gpu_4.2.2/bin/guppy_basecall_server -p 5559 -l $log_dir -x cuda:0 -c dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg &
[1] 10825
(base) [c-panz@winter211 software]$ ONT Guppy basecall server software version 4.2.2+effbaf8, client-server API version 3.2.0
config file:         /ont-guppy-gpu_4.2.2/data/dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg
model file:          /ont-guppy-gpu_4.2.2/data/template_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.jsn
log path:            /fastscratch/c-panz/test/
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:
runners per device:  4

Starting server on port: 5559
dir -s $output_dir2/bin/guppy_basecall_client -p 5559 -c dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg -i $input_
ONT Guppy basecalling software version 4.2.2+effbaf8, client-server API version 3.2.0
config file:        /ont-guppy-gpu_4.2.2/data/dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg
input path:         /fastscratch/c-panz/test/input
save path:          /fastscratch/c-panz/test/output
chunk size:         2000
records per file:   4000

Found 10 fast5 files to process.
Init time: 19 ms

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Caller time: 2304 ms, Samples called: 527521, samples/s: 228959
Finishing up any open output files.
Basecalling completed successfully.
```

**Comment by marcus1487** [comment] 2021-02-24 22:20
I would recommend a virtual environment. They are a little bit cleaner and separated from any base environment (found in conda). To install megalodon try:
```
python -m venv --copies --prompt megalodon venv
source venv/bin/activate
pip install numpy
pip install megalodon
```

**Comment by PanZiwei** [comment] 2021-02-24 22:34
@marcus1487 
Hi, that's exactly what I did to use Megalodon. I created a virtual environment, installed megalodon, initiated an interactive GPU node, activated the environment, run Megalodon to train a Modified Base Model. Then I encountered the issue as I listed https://github.com/nanoporetech/megalodon/issues/98#issuecomment-782179615..
```
(megalodon2.2.10_guppy4.2.2) [c-panz@winter-log2 ~]megalodon ecoli_k12_fast5s/ \
    --outputs signal_mappings \
    --reference ecoli_k12_reference.fa \
    --devices 0 --processes 40 \
    --ref-mods-all-motifs m 5mC CCWGG 1 \
    --guppy-server-path ${GUPPY_PATH}/guppy_basecall_server \
    --devices 0 \
    --processes ${NPROC}   
[17:30:48] Running Megalodon version 2.2.10
[17:30:48] Loading guppy basecalling backend
****************************************************************************************************
	ERROR: Guppy server initialization failed. See guppy logs in --output-directory for more details.
		Try running the guppy server initialization command found in log.txt in order to pinpoint the source of this issue.
****************************************************************************************************
```

```
2021-02-24 17:30:48.514336 [guppy/message] ONT Guppy basecall server software version 4.2.2+effbaf8, client-server API version 3.2.0
config file:         /ont-guppy-gpu_4.2.2/data/dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg
model file:          /ont-guppy-gpu_4.2.2/data/template_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.jsn
log path:            /guppy_log
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:
runners per device:  4

2021-02-24 17:30:48.516260 [guppy/info] crashpad_handler not supported on this platform.
2021-02-24 17:30:48.517889 [guppy/info] Listening on port 33835.
2021-02-24 17:30:48.532213 [guppy/error] CUDA error at /builds/ofan/ont_core_cpp/ont_core/common/cuda_common.cpp:203: CUDA_ERROR_NO_DEVICE
2021-02-24 17:30:48.532309 [guppy/warning] An error occurred initialising the basecaller. Aborting.
```

**Comment by marcus1487** [comment] 2021-02-24 22:43
Have you tried the guppy server command exactly as found in the megalodon `log.txt` file in this new environment? From previous logs I think this is it: `/ont-guppy-gpu_4.2.2/bin/guppy_basecall_server -p auto -l /results/guppy_log -c dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg --post_out -x cuda:0 --num_callers 10 --ipc_threads 80`

The current hypothesis is that something in the conda environment is not allowing the CUDA setup to function correctly. This was the reason for the virtual environment install suggestion as opposed to the conda environment install. Even deactivating the conda base environment might help here.

**Comment by PanZiwei** [comment] 2021-02-24 23:01
As I mentioned earlier https://github.com/nanoporetech/megalodon/issues/98#issuecomment-785169826 I encoutered the error inside the conda environment:
```
(megalodon2.2.10_guppy4.2.2) [c-panz@winter-log2 software]$ input_dir="/fastscratch/c-panz/test/input"
(megalodon2.2.10_guppy4.2.2) [c-panz@winter-log2 software]$ output_dir="/fastscratch/c-panz/test/output"
(megalodon2.2.10_guppy4.2.2) [c-panz@winter-log2 software]$ log_dir='/fastscratch/c-panz/test/'
(megalodon2.2.10_guppy4.2.2) [c-panz@winter-log2 software]$ ont-guppy-gpu_4.2.2/bin/guppy_basecall_server -p 5559 -l $log_dir -x cuda:0 -c dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg
ONT Guppy basecall server software version 4.2.2+effbaf8, client-server API version 3.2.0
config file:         /ont-guppy-gpu_4.2.2/data/dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg
model file:          /ont-guppy-gpu_4.2.2/data/template_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.jsn
log path:            /test/
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:
runners per device:  4

[guppy/error] main: CUDA error at /builds/ofan/ont_core_cpp/ont_core/common/cuda_common.cpp:203: CUDA_ERROR_NO_DEVICE
[guppy/warning] main: An error occurred initialising the basecaller. Aborting.
```

But when I deactivated the environment and run Guppy in the base environment(No Megalodon installed) everything is OK: https://github.com/nanoporetech/megalodon/issues/98#issuecomment-785331912

**Comment by marcus1487** [comment] 2021-02-24 23:03
Right. I understand. I am wondering if this same error is replicated outside of the conda environment, but inside of a new virtual environment (not a conda virtual environment) installed as mentioned previously (https://github.com/nanoporetech/megalodon/issues/98#issuecomment-785422803).

**Comment by PanZiwei** [comment] 2021-02-24 23:10
To summary, it seems that the error only occurs in the conda virtual environment with Megalodon? 
Here is the package list for my virtual environment in case you need it...
[requirements.txt](https://github.com/nanoporetech/megalodon/files/6039382/requirements.txt)

**Comment by marcus1487** [comment] 2021-03-05 00:39
To be completely clear, is the virtual environment `megalodon2.2.10_guppy4.2.2` a conda environment? If so could you try to install megalodon in a python virtual environment instead of a conda virtual environment. See instructions for creating a python virtual environment here: https://docs.python.org/3/tutorial/venv.html

**Comment by ginolhac** [comment] 2021-03-09 13:04
Hi,
just to let you know that in the official [documentation](https://nanoporetech.github.io/megalodon/):
it is stated:
> ## Installation 
>`pip` and `conda` are the recommended installation interfaces for Megalodon. 

if virtualenv is to be used, I think it should clearly updated.
Best wishes

**Comment by marcus1487** [comment] 2021-03-10 21:06
The recommendation will be amended in the next release to indicate that `pip` is the recommended installation method. 

`pip` will install megalodon into many environment types (system root, virtualenv, conda, etc.). This choice is left up to the user. I personally find python virtual environments to work in more settings than conda environments, but this is just a personal preference. Megalodon has worked within conda, but we don't have the maintenance capacity to test a wide range of environment settings.

**Comment by marcus1487** [comment] 2021-04-01 23:14
Recommendation is updated in the README.

**Closed by marcus1487** 2021-04-01 23:14 UTC
Labels: guppy, question
