### ISSUE TITLE
Using miscalled bases for training methylation callers

### ISSUE THREAD

**Issue by CodingKaiser** [nanoporetech/megalodon#208] opened 2021-11-01 09:51 UTC
Hello Megalodon Team, 

I am currently using some training data to train an 5mC caller and am noticing that during the course of producing the signal mappings, per_read_mods, and calibration files, a lot of sequences which contain our methylated motif of interest, and would therefore be valuable for training, are being thrown out. This appears to be happening because guppy is failing to correctly call the position in question as a C.

Specifically, we have input fast5 sequences containing the following motif sequence, where the C in the second-to-last position is methylated.

`ATTATCACCGCGTCCATNNNNCG`

These motifs are being miscalled in great numbers as:

`ATTATCACCGCGTCCATNNNNAG`
`ATTATCACCGCGTCCATNNNNTG`
`ATTATCACCGCGTCCATNNNNGG`

presumably because this position is methylated. All other positions have very few miscalls.

We are losing about a third of sequences with this motif, even though we have a virtual guarantee that this position contains a C. Is there some way we could "rescue" these sequences and use them down the line when we train our taiyaki model? It would obviously be of great interest for us to be able to improve the underlying guppy basecalling model such that these sequences can be considered.

**Comment by marcus1487** [comment] 2021-11-01 14:27
Megalodon does not filter reads out from the `--outputs signal_mappings` due to mismatches in the basecalling. There are a number of other filters applied to reads throughout the dataset preparation though. Could you provide your full megalodon command and the output summary so I could have a better idea what filters may be removing these reads from your final training set.

**Comment by CodingKaiser** [comment] 2021-11-04 15:01
Sure thing. These are the steps I perform:

`megalodon \
        hp_fast5/ \
        --guppy-server-path $guppy_path \
        --overwrite \
        --outputs per_read_mods signal_mappings \
        --reference /cluster/home/falnoe/ont/genome/pSpCas9hp.fa \
        --ref-mods-all-motifs m 5mC ATTATCACCGCGTCCATNNNNCG 21 \
        --ref-mods-all-motifs m 5mC GTTCGCACCGCGTCCATATATCG 21 \
        --processes 10 \
        --devices 0`
to generate the signal mappings and per-read-mods-file.

Then, to do the calibration:
`
megalodon_extras calibrate generate_modified_base_stats megalodon_results/ --ground-truth-data ground_truth.csv --strand-specific-sites
megalodon_extras calibrate modified_bases --out-pdf calibration.pdf --overwrite
`

**Comment by marcus1487** [comment] 2021-11-04 19:08
The calibration step should come after the model training. This megalodon command looks correct and should produce the desired training dataset. How have you determined that the training data contains the basecalling errors?

**Comment by CodingKaiser** [comment] 2021-11-09 07:52
I have determined it by searching for the motif sequence in the fastq file. We first filter all sequences which contain the motif(s) allowing for one mismatch. Taking these sequences, I search for the motif exactly, i.e. no mismatches beyond the variable region, to determine how many "useful" sequences we have. 

For motif 1, we get 9'485 sequences, for motif 2 we get 8'435 sequences.

Indeed, there appears to be additional filtering occurring like you mentioned because when I run `modified base stats`, I end up getting the following output:

```text
Data summary:
	mod	mod_N	can_N
	m	15697	6166050
```

indicating we are losing quite a few sequences even beyond the no-mismatch filter criteria.

Also, why does calibartion have to occur after training? I run it immediately after I generate the signal mappings, per_read_mods because, as far as I can tell, it only operates on the files from the previous steps and the model training does not modify them.

**Comment by marcus1487** [comment] 2021-11-09 17:06
I'm not sure I am following the entire target pipeline here. The motif of interest missing from the fastq file is unrelated to what goes into the mapped signal file. The mapped signal file megalodon produces uses the reference bases for a mapping and not the basecalls. So if a read maps over the motif of interest in the reference this sequence will be in the training file.

The command you posted also should not output a FASTQ file, so from where is this FASTQ derived?

Calibration is a step to calibrate the modified base scores produced by a model. Thus a model must be produced in order to have modified base score to compare against. You can re-calibrate a model that has already been trained to detect a modified base of interest, but it is still after the training of that modified base model.

For the distribution of mod and canonical sites this also makes sense. Every C outside of your motif of interest is included in training and will be included in this count. The motif is quite long so there are clearly many more Cs outside this motif than within this motif.

**Comment by CodingKaiser** [comment] 2021-11-11 14:22
The fastq files I mentioned we generated separately when we qc'd our samples. I apologize if this caused confusion. Because we get a great deal of sequences which have no overlap with the motifs, we subset our original sequencing data to include only reads which have overlap. To do this, we do basecalling, filter the fastqs for our region of interest, map them and then take the ids of the sequences with a primary mapping to subset the fast5 using the `ont_fast5_api`.

The distribution of mod and canonical sites makes sense, but the absolute number of mod sites found suggests that a great number of reads are filtered out as we would expect 17'920 sites if we go by just sequence alone. Instead we get 15'697. I am not sure why the number of sequences after basecalling and mapping by megalodon is lower than what we get.

Coming back to the original point, we would be interested to "rescue" sequences which are almost certainly motifs of interest (correct alignment and a mismatch at the methylated C position) but are miscalled by guppy. Is something like this possible?

**Comment by marcus1487** [comment] 2021-11-11 14:27
So it sounds like the issue is upstream of megalodon in your pre-processing of the FAST5 files. If megalodon does not receive the fast5 files it cannot rescue them.

I would suggest that instead of filtering no the basecalls, you filter on the reference sequence where each read maps. This will be the sequence that goes into the megalodon modified base markup.

For the difference between the number of sites you found in the basecalls and the number found in the mapped signal files, I believe this is the reverse problem. So if the basecalls make an error into your motif of interest then megalodon will undo this by taking the corresponding reference sequence and thus not mark up the modified base in that motif.

I hope this helps and best of luck in your research!

**Closed by marcus1487** 2021-11-11 14:27 UTC
Labels: question
