### ISSUE TITLE
Could not load guppy server configuration state: 'Configurations'

### ISSUE THREAD

**Issue by AlexdeMendoza** [nanoporetech/megalodon#294] opened 2022-06-10 19:50 UTC
Hi,

I have been trying to run Megalodon with Guppy-GPU (6.1.3) on a HPC and it always breaks on the same step. In the past I have been able to run Megalodon with CPU with a older version of Guppy, but that is quite slow. So I would really like to understand what's wrong with this message, and how do you think I could fix this: 

The `guppy_basecall_server_log-2022-06-10_20-36-48.log` is:
```
2022-06-10 20:36:48.296344 [guppy/message] ONT Guppy basecall server software version 6.1.3+cc1d765d3, client-server API version 11.0.0, minimap2 version 2.22-r1101
log path:            megalodon-results_allProm_5mC_CpG_container/guppy_log
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:
runners per device:  4
Use of this software is permitted solely under the terms of the end user license agreement (EULA).By running, copying or accessing this software, you are demonstrating your acceptance of the EULA.
The EULA may be found in /opt/ont/guppy/bin


2022-06-10 20:36:48.298866 [guppy/info] crashpad_handler successfully launched.
2022-06-10 20:36:48.315102 [guppy/info] Listening on port ipc:///tmp/2410059.1.all.q/0fe7-e6ea-f7aa-0be0.
2022-06-10 20:36:49.353173 [guppy/message]
Config loaded:
config file:               /data/home/btx717/storage/01-ademendoza/software/rerio/basecall_models/res_dna_r941_prom_modbases_5mC_CpG_v001.cfg
model file:                /data/home/btx717/storage/01-ademendoza/software/rerio/basecall_models/res_dna_r941_prom_modbases_5mC_CpG_v001.jsn
model version id           None
adapter scaler model file: None
2022-06-10 20:36:49.532800 [guppy/info] CUDA device 0 (compute 7.0) initialised, memory limit 16945512448B (16623599616B free)
2022-06-10 20:36:49.562658 [guppy/info] lamp_arrangements arrangement folder not found: /data/home/btx717/storage/01-ademendoza/software/rerio/basecall_models/read_splitting/lamp_arrangements
2022-06-10 20:36:49.576193 [guppy/info] lamp_arrangements arrangement folder not found: /data/home/btx717/storage/01-ademendoza/software/rerio/basecall_models/barcoding/lamp_arrangements
2022-06-10 20:36:49.631444 [guppy/message] Starting server on port: ipc:///tmp/2410059.1.all.q/0fe7-e6ea-f7aa-0be0
2022-06-10 20:36:49.654211 [guppy/info] client connection request. ["res_dna_r941_prom_modbases_5mC_CpG_v001:>timeout_interval=15000>client_name=>barcode_kits=>detect_barcodes=0>move_and_trace_enabled=1>post_out=1"]
2022-06-10 20:36:49.658267 [guppy/info] New client connected Client 1 anonymous_client_1 id: 9f4712cb-73b9-4e96-b24c-6a44fa787e89 (connection string = 'res_dna_r941_prom_modbases_5mC_CpG_v001:>timeout_interval=15000>client_name=>barcode_kits=>detect_barcodes=0>move_and_trace_enabled=1>post_out=1').
```

and the `log.txt` is:

```
[20:36:47] Running Megalodon version 2.5.0
DBG 20:36:47 : Command: """/usr/local/bin/megalodon --guppy-server-path /usr/bin/guppy_basecall_server --guppy-params  -d /data/home/btx717/storage/01-ademendoza/software/rerio/basecall_models/ --guppy-config res_dna_r941_prom_modbases_5mC_CpG_v001.cfg --guppy-timeout 600.0 --outputs basecalls mappings mod_mappings mods per_read_mods --reference Aparasiticum_flye_medaka_pilon2.fasta --processes 8 --overwrite --output-directory megalodon-results_allProm_5mC_CpG_container --devices cuda:0 --write-mods-text PromFast5/""" --- MainProcess-MainThread megalodon.py:1787
[20:36:47] Loading guppy basecalling backend
DBG 20:36:48 : Guppy version: "6.1.3" --- MainProcess-MainThread backends.py:938
DBG 20:36:48 : Pyguppy version: "6.1.3" --- MainProcess-MainThread backends.py:939
DBG 20:36:48 : guppy server init command: "/usr/bin/guppy_basecall_server -p auto -l megalodon-results_allProm_5mC_CpG_container/guppy_log -c res_dna_r941_prom_modbases_5mC_CpG_v001.cfg --quiet --post_out -x cuda:0 -d /data/home/btx717/storage/01-ademendoza/software/rerio/basecall_models/" --- MainProcess-MainThread backends.py:1016
DBG 20:36:48 : Found guppy log file: megalodon-results_allProm_5mC_CpG_container/guppy_log/guppy_basecall_server_log-2022-06-10_20-36-48.log --- MainProcess-MainThread backends.py:1032
DBG 20:36:49 : Guppy server started on port ipc:///tmp/2410059.1.all.q/0fe7-e6ea-f7aa-0be0 --- MainProcess-MainThread backends.py:973
DBG 20:36:49 : Connecting to server --- MainProcess-MainThread backends.py:872
DBG 20:36:49 : pyguppy server status: result.success --- MainProcess-MainThread backends.py:909
DBG 20:36:49 : Could not load guppy server configuration state: 'Configurations' --- MainProcess-MainThread backends.py:913
```
As other users in the Issues forum, the message I get is a "segmentation fault". 

Any idea on what might be happening? 

Thanks, 

Alex

**Comment by marcus1487** [comment] 2022-06-10 20:38
This looks like a duplicate of #292. Let's track this issue there.

**Closed by marcus1487** 2022-06-10 20:38 UTC
