### ISSUE TITLE
ont-pyguppy-client-lib 5.0.12 not on pip yet?

### ISSUE THREAD

**Issue by adbeggs** [nanoporetech/megalodon#181] opened 2021-08-08 11:03 UTC
Hi all

Just upgraded our prom software/guppy and megalodon is looking for a version of pyguppy that doesn't seem to exist on pip yet (5.0.12) - any idea when it may be available?

Thanks for the great work

Andrew

**Comment by marcus1487** [comment] 2021-08-10 13:26
Guppy 5.0.12 was not released as a standalone release to the community page. Using megalodon (or the pyguppy client interface) is not supported on other releases. It is also not recommended to run megalodon against a system-wide install of guppy (some unexpected behaviors have been observed in the past). 

I would recommend downloading the most recent guppy version from the community (5.0.11) and pointing megalodon to this download.

**Closed** 2021-08-11 17:00 UTC
Labels: guppy

**Comment by pterzian** [comment] 2021-08-30 13:09
Hi Marcus,

Having the same issues here.
Could you describe a bit more how to point megalodon to this download ?
I tried downloading+unpacking it then gave this path "guppy_5.0.11-1/opt/ont/guppy/bin/guppy_basecall_server" to the `--guppy-server-path` argument but I have some error.

thanks a lot

Paul

**Comment by a-slide** [comment] 2021-08-31 10:06
Hi @pterzian,

**Comment by pterzian** [comment] 2021-08-31 12:42
Hi @a-slide,

I don't have it at the moment I'll launch it again and come back to you. However I remember it was some library missing and I might had some file missing unpackaging the .deb using `dpkg-deb -x $DEBFILE $TARGET_DIRECTORY`

**Comment by pterzian** [comment] 2021-09-01 09:53
Hi @a-slide,

So I successfully unpackaged the guppy_5.0.11-1 deb file with dpkg. Then added this path:  `~/guppy_5.0.11/opt/ont/guppy/bin/guppy_basecall_server` to the megalodon command

Finally I have this error when running the command :

```
[11:46:48] Running Megalodon version 2.3.3
[11:46:48] Loading guppy basecalling backend
Traceback (most recent call last):
  File "/home/prom/megalodon-venv/bin/megalodon", line 8, in <module>
    sys.exit(_main())
  File "/home/prom/megalodon-venv/lib/python3.7/site-packages/megalodon/__main__.py", line 691, in _main
    megalodon._main(args)
  File "/home/prom/megalodon-venv/lib/python3.7/site-packages/megalodon/megalodon.py", line 1759, in _main
    model_info = backends.ModelInfo(backend_params, args.processes)
  File "/home/prom/megalodon-venv/lib/python3.7/site-packages/megalodon/backends.py", line 546, in __init__
    self.pyguppy_load_settings()
  File "/home/prom/megalodon-venv/lib/python3.7/site-packages/megalodon/backends.py", line 1021, in pyguppy_load_settings
    self.pyguppy_check_version(pyguppy_version_str)
  File "/home/prom/megalodon-venv/lib/python3.7/site-packages/megalodon/backends.py", line 839, in pyguppy_check_version
    'Guppy version string does not match expected pattern: "{}"'
AttributeError: 'MegaError' object has no attribute 'format'
```

thanks,

Paul

**Comment by marcus1487** [comment] 2021-09-03 22:45
This looks like a Guppy issue. Can you run `/home/prom/guppy_5.0.11/opt/ont/guppy/bin/guppy_basecall_server -v` to see the help for the guppy server version? If not then I would raise an issue on the community to inquire about guppy installation issues.

**Comment by pterzian** [comment] 2021-09-06 15:38
@marcus1487 Yes it does raise this error: 

```
/home/prom/guppy_5.0.11/opt/ont/guppy/bin/guppy_basecall_server: error while loading shared libraries: libboost_log.so.1.65.1: cannot open shared object file: No such file or directory
```

I actually just unpacked the guppy deb but I am not sure it is supposed to work like that. I also have limited knowledge and don't want to mess with the minKnow version by using an `apt-get` or so. I might ask to someone around me or posting to the community then.

thanks
