### ISSUE TITLE
ERROR: Guppy server initialization failed. "crashpad_handler not supported on this platform."

### ISSUE THREAD

**Issue by PanZiwei** [nanoporetech/megalodon#155] opened 2021-06-11 21:23 UTC
Hi I am running Megalodon 2.2.3 with Guppy-gpu 5.0.7 as backend on CUDA 11.1. I have used the configuration files `res_dna_r941_min_modbases_5mC_v001.cfg` from Rerio. I checked that the Rerio is updated, and `ont_pyguppy_client_lib` is v5.0.7. 

Can you help with this issue? Thanks!

PS: My issue is similar to https://github.com/nanoporetech/megalodon/issues/107#issuecomment-788756459, but I had not idea on how to solve it.

My running command:
```
megalodon \
    ${FAST5_PATH}/0 \
    `# output location + overwrite` \
    --output-directory ${OUTPUT_DIR}/0 \
    --overwrite \
    `# guppy options` \
    --guppy-server-path ${GUPPY_PATH}/guppy_basecall_server \
    --guppy-params "-d ./rerio/basecall_models/" \
    --guppy-config res_dna_r941_min_modbases_5mC_v001.cfg \
    --reference ${FASTA_REF} \
    --mod-motif m CG 0 \
    --devices 0 1 \
    --processes ${NPROC}
```
Here is the error message:
```
[17:15:08] Running Megalodon version 2.3.3
[17:15:08] Loading guppy basecalling backend
****************************************************************************************************
	ERROR: Guppy server initialization failed. See guppy logs in [--output-directory] for more details.
		Try running the guppy server initialization command found in log.txt in order to pinpoint the source of this issue.
****************************************************************************************************
```

The log message is below:
```
2021-06-11 17:15:08.645137 [guppy/message] ONT Guppy basecall server software version 5.0.7+2332e8d, client-server API version 7.0.0
log path:            /fastscratch/c-panz/megalodon2.2.3/0/guppy_log
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0 cuda:1
kernel path:
runners per device:  4
2021-06-11 17:15:08.645802 [guppy/info] crashpad_handler not supported on this platform.
2021-06-11 17:15:08.646156 [guppy/info] Listening on port 36429.
2021-06-11 17:15:08.792198 [guppy/info] CUDA device 0 (compute 7.0) initialised, memory limit 34089730048B (33766244352B free)
```

Best,
Ziwei

**Comment by PanZiwei** [comment] 2021-06-13 22:25
Hi, I also tried Guppy v5.0.11 but still got a similar error:
```
2021-06-13 18:24:18.677709 [guppy/message] ONT Guppy basecall server software version 5.0.11+2b6dbff, client-server API version 7.0.0
log path:            /fastscratch/c-panz/megalodon2.2.3/0/guppy_log
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0 cuda:1
kernel path:
runners per device:  4
2021-06-13 18:24:18.681440 [guppy/info] crashpad_handler not supported on this platform.
2021-06-13 18:24:18.682010 [guppy/info] Listening on port 41801.
2021-06-13 18:24:18.862468 [guppy/info] CUDA device 0 (compute 7.0) initialised, memory limit 34089730048B (33766244352B free)
2021-06-13 18:24:18.868042 [guppy/error] CUDA error at /builds/ofan/ont_core_cpp/ont_core/common/cuda_common.cpp:205: CUDA_ERROR_INVALID_DEVICE
2021-06-13 18:24:18.868123 [guppy/warning] An error occurred initialising the basecaller. Aborting.
```

**Comment by marcus1487** [comment] 2021-06-14 22:15
This looks like an issue with the GPU specifications. Does the compute environment have two GPUs available (as requested via `--devices 0 1`?

**Comment by PanZiwei** [comment] 2021-06-15 00:55
@marcus1487 Hi there are two GPUs available. I tried to use 1 GPU instead by using `--devices 0` or `--devices 1`, but still failed. But everything workes well when I used Guppy itself via the `guppy_basecaller` command with either 1 or 2 GPUs. 
Maybe something went wrong when Megalodon tried used guppy_basecall_server as background? Is it practical to use cpu version(though it will be much slower)?

**Comment by marcus1487** [comment] 2021-06-15 12:56
Megalodon generally works well with Guppy as the backend and this is the recommended running mode. Can you extract the guppy server startup command from the top of the megalodon log.txt output, run this command (which will likely fail) and report the results?

**Comment by fbrennen** [comment] 2021-06-15 13:06
Hi @PanZiwei -- the errors you're seeing have nothing to do with crashpad. The crashpad message is not an error, it's just information saved to the log (which is why it's described as `[guppy/info]` and not `[guppy/error]`). You have three different types of logs you've pasted here from guppy, by the look of it:
* In the first log, there is no guppy error (I don't know what the issue is there, but the server log shows no problems).
* In the second log, there is some issue with one of the GPUs (which is why guppy gives that `CUDA_ERROR_INVALID_DEVICE`)
* In the third log, there is a memory issue with one of the GPUs (hence that `CUDA_ERROR_ECC_UNCORRECTABLE`)

Are you using a cloud service such as AWS by chance? In my experience quite a lot of the GPUs have issues there -- in that case you have to either figure out which ones don't work, or shut the entire instance down and start a new one (hopefully with a more functional set of GPUs).

**Comment by PanZiwei** [comment] 2021-06-15 13:36
Hi @marcus1487 
Here is the result when running the startup command in the log.txt:
```
(megalodon2.3.3) [c-panz@winter203 ~]$ /projects/li-lab/Ziwei/Anaconda3/envs/megalodon2.3.3/bin/megalodon \ 
/pod/2/li-lab/Ziwei/Nanopore/data/single_read/0 \
--output-directory /fastscratch/c-panz/megalodon2.2.3/0 \
--overwrite \
--outputs basecalls mod_basecalls mappings \
per_read_mods mods mod_mappings \
per_read_refs signal_mappings \
--guppy-server-path /software/ont-guppy-gpu_5.0.7/bin/guppy_basecall_server \
--guppy-params -d /software/rerio/basecall_models/ \
--guppy-config res_dna_r941_min_modbases_5mC_v001.cfg\
 --guppy-timeout 500 \
 --samtools-executable /Ziwei/Anaconda3/envs/megalodon2.3.3/bin/samtools \
 --sort-mappings --mappings-format bam \
 --reference /Ziwei/Nanopore/data/reference/hg38.fa \
 --mod-motif m CG 0  \
 --mod-aggregate-method binary_threshold  \
 --mod-output-formats  bedmethyl wiggle \ 
 --write-mods-text --write-mod-log-probs  \
 --devices 0 --processes 40
usage: megalodon [-h] [--guppy-config GUPPY_CONFIG] [--guppy-server-path GUPPY_SERVER_PATH] [--live-processing]
                 [--outputs {basecalls,mod_basecalls,mappings,per_read_variants,variants,variant_mappings,per_read_mods,mods,mod_mappings,signal_mappings,per_read_refs} [{basecalls,mod_basecalls,mappings,per_read_variants,variants,variant_mappings,per_read_mods,mods,mod_mappings,signal_mappings,per_read_refs} ...]]
                 [--output-directory OUTPUT_DIRECTORY] [--overwrite] [--mappings-format {bam,cram,sam}] [--reference REFERENCE] [--haploid] [--variant-filename VARIANT_FILENAME]
                 [--mod-motif BASE MOTIF REL_POSITION] [--processes PROCESSES] [--devices DEVICES [DEVICES ...]] [--help-long] [--rna] [-v]
                 fast5s_dir
megalodon: error: argument --guppy-params: expected one argument
```
The error is different from the log.txt file inside.

@fbrennen 
I didn't use cloud services such as AWS, I am using the GPU-based cluster in the institute.

I have an interactive job, so I think the first log is the one that appears in the interactive mode(See below), the second one is the `log.txt` file, the third one is under `guppy_log/` folder `guppy_basecall_server_log-time.log` right?
```
[09:27:55] Running Megalodon version 2.3.3
[09:27:55] Loading guppy basecalling backend
****************************************************************************************************
	ERROR: Guppy server initialization failed. See guppy logs in [--output-directory] for more details.
		Try running the guppy server initialization command found in log.txt in order to pinpoint the source of this issue.
****************************************************************************************************
```

**Comment by marcus1487** [comment] 2021-06-15 13:41
This is the megalodon startup command. There should be a command that starts with the `guppy_basecall_server` path. Could you run this command and report the results?

**Comment by PanZiwei** [comment] 2021-06-15 13:44
@marcus1487 See below:
```
(megalodon2.3.3) [c-panz@winter203 ~]$ /software/ont-guppy-gpu_5.0.7/bin/guppy_basecall_server -p auto -l /fastscratch/c-panz/megalodon2.2.3/0/guppy_log -c res_dna_r941_min_modbases_5mC_v001.cfg --post_out --quiet -x cuda:0 -d /software/rerio/basecall_models/
[guppy/error] main: CUDA error at /builds/ofan/ont_core_cpp/ont_core/common/cuda_common.h:113: CUDA_ERROR_INVALID_VALUE
[guppy/warning] main: An error occurred initialising the basecaller. Aborting.
```

**Comment by marcus1487** [comment] 2021-06-15 16:24
I don't see anything wrong with this command and this error does not match the errors from previous runs. Could you change the `-l` log output argument to a new location since this parent directory may not exist now. Could you also ensure that the `-d` data directory exists and the selected model has been downloaded in that rerio location?

**Comment by PanZiwei** [comment] 2021-06-15 16:29
Hi I checked that the data directory exists and the model is downloaded already.
I changed the -l to a new location and here is the same error message in the interactive node:
```
(megalodon2.3.3) [c-panz@winter203 sif]$ /software/ont-guppy-gpu_5.0.7/bin/guppy_basecall_server -p auto -l /fastscratch/c-panz/log -c res_dna_r941_min_modbases_5mC_v001.cfg --post_out --quiet -x cuda:0 -d /software/rerio/basecall_models/
[guppy/error] main: CUDA error at /builds/ofan/ont_core_cpp/ont_core/common/cuda_common.h:113: CUDA_ERROR_INVALID_VALUE
[guppy/warning] main: An error occurred initialising the basecaller. Aborting.
```
The corresponding log file (which is consistent with the error in the previous post):
```
2021-06-15 12:27:41.068593 [guppy/message] ONT Guppy basecall server software version 5.0.7+2332e8d, client-server API version 7.0.0
log path:            /fastscratch/c-panz/log
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:
runners per device:  4
2021-06-15 12:27:41.073884 [guppy/info] crashpad_handler not supported on this platform.
2021-06-15 12:27:41.074375 [guppy/info] Listening on port 38556.
2021-06-15 12:27:41.279196 [guppy/info] CUDA device 0 (compute 7.0) initialised, memory limit 34089730048B (33766244352B free)
2021-06-15 12:27:51.062003 [guppy/error] CUDA error at /builds/ofan/ont_core_cpp/ont_core/common/cuda_common.h:113: CUDA_ERROR_INVALID_VALUE
2021-06-15 12:27:51.064217 [guppy/warning] An error occurred initialising the basecaller. Aborting.
```

**Comment by marcus1487** [comment] 2021-06-15 16:34
Could you try to upgrade to guppy 5.0.11? It is possible this may be a bug that was fixed in the latest version of guppy.

**Comment by PanZiwei** [comment] 2021-06-15 16:38
Unfortunately I got the same error:
```
(megalodon2.3.3) [c-panz@winter203 sif]$ /pod/2/li-lab/software/ont-guppy-gpu_5.0.11/bin/guppy_basecall_server -p auto -l /fastscratch/c-panz/log -c res_dna_r941_min_modbases_5mC_v001.cfg --post_out --quiet -x cuda:0 -d /pod/2/li-lab/software/rerio/basecall_models/
[guppy/error] main: CUDA error at /builds/ofan/ont_core_cpp/ont_core/common/cuda_common.h:113: CUDA_ERROR_INVALID_VALUE
[guppy/warning] main: An error occurred initialising the basecaller. Aborting.
```

**Comment by marcus1487** [comment] 2021-06-15 17:04
Using the same command as yours with a fresh rerio and guppy install I am getting a successfully started guppy server. This may be an environment issue or something else. Hopefully the guppy devs can find a solution for you, but this does not appear to be an issue with megalodon, but instead an issue with guppy in your environment.

**Comment by PanZiwei** [comment] 2021-06-16 04:00
Let me contact IT to check my environment and contact Guppy for help to see whether this one can be solved or not.

Meanwhile, would you mind sharing what version of Guppy and what model of rerio you used for testing? Thanks!

**Comment by marcus1487** [comment] 2021-06-16 04:19
I am using a fresh download of 5.0.11 in my local directory and the following commands to prepare and run the guppy server:

```
git clone https://github.com/nanoporetech/rerio
./rerio/download_model.py rerio/basecall_models/res_dna_r941_min_modbases_5mC_v001
./ont-guppy/bin/guppy_basecall_server \
    -p auto \
    -l ./guppy_log \
    -c res_dna_r941_min_modbases_5mC_v001.cfg \
    --post_out \
    --quiet \
    -x cuda:0 \
    -d ./rerio/basecall_models/
```

**Comment by PanZiwei** [comment] 2021-06-17 20:25
Update:
I redownloaded Guppy GPU 5.0.11 on my cluster and run the command above, but the process is killed, and the log file is still crashed:
```
2021-06-17 16:23:28.893836 [guppy/message] ONT Guppy basecall server software version 5.0.11+2b6dbff, client-server API version 7.0.0
log path:            ./guppy_log
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:
runners per device:  4
2021-06-17 16:23:28.895649 [guppy/info] crashpad_handler not supported on this platform.
2021-06-17 16:23:28.896134 [guppy/info] Listening on port 36770.
2021-06-17 16:23:29.040526 [guppy/info] CUDA device 0 (compute 6.0) initialised, memory limit 17071734784B (16804216832B free)
```

**Comment by marcus1487** [comment] 2021-06-17 20:56
This output does not indicate any errors. Can you ask your server admins to check the reason the job was killed?

For running guppy from a local directory, I simply copy the appropriate guppy download to a a directory of choice and un-compress the file. This is generally the only setup required assuming CUDA drivers are available on the server. If CUDA drivers are not available I don't believe GPU-compatible guppy will run.

**Comment by PanZiwei** [comment] 2021-06-17 21:15
I rerun the job again with the default HAC model, this time the job is not killed, but the process is paused again with the `CUDA_ERROR_INVALID_VALUE` issue.
```
[guppy/error] main: CUDA error at /builds/ofan/ont_core_cpp/ont_core/common/cuda_common.h:113: CUDA_ERROR_INVALID_VALUE
[guppy/warning] main: An error occurred initialising the basecaller. Aborting.
```

The CUDA driver is installed on our institute cluster, not on my own computer. So it may be challenging to run the latest Megalodon locally in this case.

**Comment by PanZiwei** [comment] 2021-06-18 20:15
Hi, I think I partly solved the problem since it seems to be relevant to the memory stuff.

Can you provide the GPU/CPU/memory requirement to host the Guppy server or initiate Megalodon? Thank you!

**Closed** 2021-06-29 15:38 UTC
Labels: guppy, question

**Comment by Lucas-Servi** [comment] 2022-06-09 19:40
Link to the post? Having the same issue over here with guppy 6.1.7 (RTX3050 Laptop)

**Comment by Modernism-01** [comment] 2023-08-07 12:47
hello, I also run the guppy_basecall_server (6.01+652ffd1) for test, the demo is attached below:
./guppy_basecall_server \
    -p auto \
    -l ./guppy_log \
    -c res_dna_r941_min_modbases_5mC_CpG_v001.cfg \
    --post_out --quiet -x cuda:0 \
    -d ~/04.software/03.Guppy/rerio/basecall_models/ \
    --num_callers 1 \
    --gpu_runners_per_device 1 \

I got the same error:

2023-08-07 20:41:00.629988 [guppy/message] ONT Guppy basecall server software version 6.0.1+652ffd1, client-server API version 10.0.0
log path:            ./guppy_log
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     1
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:         
runners per device:  1
2023-08-07 20:41:00.632709 [guppy/info] crashpad_handler not supported on this platform.
2023-08-07 20:41:00.634020 [guppy/info] Listening on port ipc:///tmp/fa04-f512-e15f-ac7e.
2023-08-07 20:41:01.832690 [guppy/info] CUDA device 0 (compute 8.6) initialised, memory limit 25447170048B (25181093888B free)
2023-08-07 20:41:01.844788 [guppy/info] CUDA device 0 reached memory limit while trying to allocate 0 bytes, currently at 64/25447170048
2023-08-07 20:41:01.845475 [guppy/error] CUDA error at /builds/ofan/ont_core_cpp/ont_core/barcoding/barcode_cuda.cpp:77: CUDA_ERROR_INVALID_VALUE. Error initialising basecall server using port: ipc://auto. Aborting.
2023-08-07 20:41:01.846461 [guppy/message] The basecall server has shut down successfully.

I have no choice but to ask for your help, how could I solve this problem? Thank you very much.
