### ISSUE TITLE
--guppy-config question

### ISSUE THREAD

**Issue by DiegoZavallo** [nanoporetech/megalodon#276] opened 2022-04-21 17:46 UTC
Hi, I´m fairly new with ONT data, and I want to run megadolon to call modified bases on Paspalum notatum (a grass). When I run it with default parameters it works just fine, but I was wondering if I could change the default model of `--guppy-config` to one specific for mod bases. I look up for the listed on `--list-supported-guppy-configs` and I choose `res_dna_r941_prom_modbases_5mC_v001.cfg` which (if I understood correctly) correspond to **rerio** basecalling models, but it returns this error:

> Running Megalodon version 2.5.0
> ******************** WARNING: "mods" output requested, so "per_read_mods" will be added to outputs. ********************
> [14:12:45] Loading guppy basecalling backend
> ****************************************************************************************************
> 	ERROR: Guppy server initialization failed. See guppy logs in [--output-directory] for more details.
> 		Try running the guppy server initialization command found in log.txt in order to pinpoint the source of this issue.
> ****************************************************************************************************
> 

This is my code:

`megalodon ./ --guppy-server-path /home/minion/ont-guppy/ont-guppy/bin/guppy_basecall_server --guppy-config res_dna_r941_prom_modbases_5mC_v001.cfg --remora-modified-bases dna_r9.4.1_e8 fast 0.0.0 5hmc_5mc CG 0 --outputs mappings mod_mappings mods --reference Paspalum_notatum_genome.fasta --devices 0 --processes 20`

I used the remora model for modified bases but I thought that I could "give" guppy a more mod base specific model besides the remora one.

Maybe I´m thinking this all wrong.

And another side question, I noticed the `--mod-motif` parameter and the example is for CpG context. As I mentioned, I´m working with plants. Could I add this option and ask specific motif that are´nt CpG, like CHG and CHH important in plants?

Any insight would help a lot

Thanks

Diego

**Comment by marcus1487** [comment] 2022-04-21 23:20
The Remora models were specifically trained against the canonical models. The modified base performance for Remora models would be degraded when used with the old-style modified base models. For the all-context 5mC model, we do not currently have a high quality model, but this is a very high priority internally. Once trained we will include this in Remora as well as other production basecallers. Also note that the mod-motif argument is overridden by the remora model settings.

For more info on the guppy init error the contents of the guppy log would be very helpful.

**Comment by DiegoZavallo** [comment] 2022-04-25 20:02
Thanks Marcus for your reply.
I think I understood your response, so I run the command with the default models as in the megalodon description.
This time I try to run it with more files but I think I´m getting out of memory.
I have around 20 files of ~500Mb each but when the input queue capacity extract_signal gets to 100% at some point its stop running (or at least I think it does).
![image](https://user-images.githubusercontent.com/29485786/165161943-ae158d58-b83d-4923-be72-3979ec3ac33b.png)

This is what I have, and stay that way.
I tried to run it with fewer files, but I only get it done when I used only one file!
I also added the `--num-read-enumeration-threads` option to 14 threads but eventually the same happens. 
Our GPU machine have an Intel Core i7-107000k CPU 3.80Ghz with 16CPU and a NVIDIA GeForce RTX 3060/PCle/SSE2

And this is de the code I run:
`megalodon ./ --guppy-server-path /home/minion/ont-guppy/ont-guppy/bin/guppy_basecall_server --guppy-config dna_r9.4.1_450bps_fast.cfg --remora-modified-bases dna_r9.4.1_e8 fast 0.0.0 5hmc_5mc CG 0 --outputs mappings mod_mappings mods --write-variants-text --num-read-enumeration-threads 14 --reference ./subset_Q4188/Paspalum_notatum_genome.fasta --devices 0 --processes 20`

Could I have some RAM issues?
We usually use it for sars-cov2 sequencing but I thought that for a subset of plant data would work as well. 

Any hint would be appreciated

Best

Diego

**Comment by marcus1487** [comment] 2022-04-25 20:22
This looks like output from an older guppy version. Could you update guppy (and pyguppy with matching version) and try your command again?

**Comment by marcus1487** [comment] 2022-05-19 22:15
From your screenshot it looks like you might still be using an older version of guppy/pyguppy. The `Connection to server as` spam lines were fixed in guppy 6 release. Can you confirm from the megalodon `log.txt` file that guppy and pyguppy were updated?

For the `input queue capacity extract_signal` going to 100%, this is expected. As noted in the output (without the guppy spam lines), if this progress bar remains empty, this indicates that signal extraction is a bottleneck. The signal queue being full indicates that signal is sitting in the queue waiting to be basecalled. Since basecalling is generally the bottleneck, this is the expected behavior.

After checking the updated pyguppy and guppy versions the next best bet to reduce memory would be to reduce the `--processes` value. The read workers should not use very much memory, but it is possible with ultralong reads that the signal data becomes too large. Fewer workers should help here.

**Comment by DiegoZavallo** [comment] 2022-05-20 15:04
Hi Marcus, I just realize that I was running megalodon with the older version of guppy. (Now I fix it). Despite of that, it finish when I used the index file instead of the fasta for the reference and also lowering the --processes to 10. The RAM made up to ~20Gb and hold.

However there are some things that I don´t understand:
 Regardless the amount of fast5 files that I use as input the total reads number is always the same (78132). Why is that? How can I know the total reads that megalodon use for the basecalling? As I told you before I used a subset of reads, now I used 20 files of 500mb. 
After the read processing step finish, the subsequent process are very quick. I thought that the basecalling process would take much longer, but altogether it only took 30 minutes.

For the subsequent analysis what files do you recommend to use? The modified_bases.5mC.bed? The per_read_modified_base_calls.tab? (I used the megalodon_extras to create de .tab instead of .db

I noticed that the bases with most coverage (depth) have 79x, but most of them have very few (0-5x). Do you recommend to filter out low coverage or filter by the mod_log_prob?

Thanks

Diego

**Comment by marcus1487** [comment] 2022-05-20 15:30
How are you providing the FAST5s? Megalodon will search recursively from the location specified. I generally softlink subsets of FAST5 files to a new directory when running on a small subset. You can also specify the `--num-reads` option for quick testing.

For the basecalling speed, the fast model is indeed quite fast, though I would highly recommend the high or super accuracy models (and matching remora model) for the best modified base results.

For the subsequent analyses, this is highly dependent upon the downstream goals. Without a goal for the analysis it is hard to suggest the right format.

Again the low coverage filter depends on the final targets, but for many analyses filtering low coverage sites is recommended.

**Comment by DiegoZavallo** [comment] 2022-05-20 16:29
Marcus, thanks for the quick reply
The data I´m using came from a collaborator who gave my the fasta5 files. He did the subselection  of the files based on homology on apomixis markers from two tetraploid genotype of Paspalum (a grass). I only run one genotype so far and put the 20 files in a separated folder. I guess that´s why the coverage is restricted to specific regions.

Regarding the subsequent analysis, the idea is to compare methylation proportion between genotypes, hopping to find DMRs.
I have experience with bisulfite analysis with Illumina usign Bismark and then Methylkit.
Do you recommend to run it with the bisulfite option like `--mod-map-base-conv C T --mod-map-base-conv Z C  `?
I don´t see the option for filtering low coverage, is on the `--help-long`?
thanks

**Comment by marcus1487** [comment] 2022-05-20 17:18
The bisulfite option is only applicable to the mod_mappings and mod_basecalls outputs and is mostly deprecated now that the community has developed the modbam tags in sam/bam format. Most differential methylation pipelines will accept a bedmethyl file, but please raise those issues with the downstream tools if none of the megalodon outputs are acceptable as most of the community formats are output from megalodon.

**Closed by marcus1487** 2022-05-20 17:18 UTC
