### ISSUE TITLE
Error Running megalodon-2.3.5

### ISSUE THREAD

**Issue by onkar2470** [nanoporetech/megalodon#214] opened 2021-11-09 16:58 UTC
I am running the megalodon-2.3.5 with guppy Version 5.0.11, python 3.8.12 however I am getting following error:

******************** WARNING: "mods" output requested, so "per_read_mods" will be added to outputs. ********************
[22:06:18] Loaded model calls canonical alphabet ACGT and modified bases m=5mC (alt to C)
Traceback (most recent call last):
  File "/home/tej/anaconda2/envs/megalodon/bin/megalodon", line 8, in <module>
    sys.exit(_main())
  File "/home/tej/anaconda2/envs/megalodon/lib/python3.8/site-packages/megalodon/__main__.py", line 726, in _main
    megalodon._main(args)
  File "/home/tej/anaconda2/envs/megalodon/lib/python3.8/site-packages/megalodon/megalodon.py", line 1775, in _main
    args, mods_info = parse_mod_args(
  File "/home/tej/anaconda2/envs/megalodon/lib/python3.8/site-packages/megalodon/megalodon.py", line 1448, in parse_mod_args
    mods_info = mods.ModInfo(
  File    #@@"/home/tej/anaconda2/envs/megalodon/lib/python3.8/site-packages/megalodon/mods.py", line 2211, in __init__
    assert (
**AssertionError: Alphabet (ACGT) and model number of modified bases (-41) do not agree.**

The command I used is :

megalodon fast5/ --outputs mods --reference ref.fasta --mod-motif m CG 0 --write-mods-text --processes 10 --guppy-server-path /usr/bin/guppy_basecall_server --guppy-params "-d  rerio/basecall_models --num_callers 10" --guppy-timeout 400 --guppy-config res_dna_r941_min_modbases_5mC_CpG_v001.cfg --overwrite --output-directory ./megalodon_out

I tried same command with megalodon-2.3.4 with all other tools were same and the command ran without error.

Is this some bug in the latest version or I am missing something so as to run the command successfully.

Thank you
Regards
Onkar

**Comment by marcus1487** [comment] 2021-11-09 17:25
This is a bug in 2.3.5. It has been fixed on github, but not in a release as of yet. 

Duplicate of #204

**Closed by marcus1487** 2021-11-09 17:25 UTC
Labels: duplicate
